import React, { useRef, useState } from 'react';
import { UploadCloud, X, LoaderCircle } from 'lucide-react';
import { api } from '../api';
import * as pdfjsLib from 'pdfjs-dist';
import pdfWorker from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
pdfjsLib.GlobalWorkerOptions.workerSrc = pdfWorker;
const active = { merge: { endpoint: '/pdf/merge', multi: true }, split: { endpoint: '/pdf/split' }, 'remove-pages': { endpoint: '/pdf/remove-pages' }, 'from-images': { endpoint: '/pdf/from-images', multi: true, images: true }, 'office-to-pdf': { endpoint: '/pdf/office-to-pdf', documents: true }, 'to-word': { endpoint: '/pdf/from-pdf?format=word' }, 'to-powerpoint': { endpoint: '/pdf/from-pdf?format=powerpoint' }, 'to-excel': { endpoint: '/pdf/from-pdf?format=excel' }, rotate: { endpoint: '/pdf/rotate' }, watermark: { endpoint: '/pdf/watermark' }, 'page-numbers': { endpoint: '/pdf/page-numbers' }, crop: { endpoint: '/pdf/crop' }, 'edit-text': { endpoint: '/pdf/edit-text' }, forms: { endpoint: '/pdf/forms' }, 'to-jpg': { endpoint: '/pdf/to-jpg' }, 'to-png': { endpoint: '/pdf/to-jpg' } };
export default function FileProcessorModal({ tool, visitorId, onClose, onCompleted }) {
  const input = useRef(); const [files, setFiles] = useState([]); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [option, setOption] = useState(tool.action === 'watermark' ? 'CONFIDENTIAL' : tool.action === 'crop' ? '5' : tool.action === 'edit-text' ? 'Edited with Aharnish PDF' : tool.action === 'forms' ? 'Your answer' : tool.action === 'rotate' ? '90' : '1');
  const config = active[tool.action]; const choose = list => { setError(''); setFiles([...list]); };
  async function process() { if (!config || !files.length) return; setBusy(true); setError(''); try { const size = files.reduce((total, f) => total + f.size, 0) / 1024; if (tool.action === 'to-jpg' || tool.action === 'to-png') { const pdf = await pdfjsLib.getDocument({ data: await files[0].arrayBuffer() }).promise; const page = await pdf.getPage(1); const viewport = page.getViewport({ scale: 2 }); const canvas = document.createElement('canvas'); canvas.width = viewport.width; canvas.height = viewport.height; await page.render({ canvasContext: canvas.getContext('2d'), viewport }).promise; const type = tool.action === 'to-png' ? 'image/png' : 'image/jpeg'; const blob = await new Promise(resolve => canvas.toBlob(resolve, type, .92)); if (!blob) throw new Error('Could not create the image.'); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `${files[0].name.replace(/\.pdf$/i, '')}-page-1.${tool.action === 'to-png' ? 'png' : 'jpg'}`; link.click(); URL.revokeObjectURL(url); await api.post('/track-download', { visitorId, toolUsed: tool.name, originalFileName: files[0].name, fileSizeKb: size }); onClose(); onCompleted?.(); return; } const form = new FormData(); if (config.multi) files.forEach(f => form.append('files', f)); else form.append('file', files[0]); if (['split', 'remove-pages'].includes(tool.action)) form.append('pages', option); if (tool.action === 'rotate') form.append('angle', option); if (tool.action === 'watermark' || tool.action === 'edit-text') form.append('text', option); if (tool.action === 'crop') form.append('margin', option); if (tool.action === 'forms') form.append('label', option); const { data } = await api.post(config.endpoint, form); await api.post('/track-download', { visitorId, toolUsed: tool.name, originalFileName: files[0].name, fileSizeKb: size }); window.location.assign(`${api.defaults.baseURL}/download/${encodeURIComponent(data.filename)}`); onClose(); onCompleted?.(); } catch (e) { setError(e.response?.data?.error || e.message || 'Something went wrong. Please try a valid file.'); } finally { setBusy(false); } }
  const optionLabel = tool.action === 'remove-pages' ? 'Pages to remove' : tool.action === 'crop' ? 'Crop margin (%)' : tool.action === 'edit-text' ? 'Text to add on page one' : tool.action === 'forms' ? 'Form-field placeholder' : null;
  return <div className="backdrop" onMouseDown={onClose}><section className="modal" onMouseDown={e => e.stopPropagation()}><button className="close" onClick={onClose}><X /></button><h2>{tool.name}</h2>{config ? <><p className="modal-copy">Upload your {config.images ? 'JPG or PNG images' : config.documents ? 'Word, Excel, PowerPoint, or HTML document' : 'PDF'} and we’ll process it securely.</p><div className="dropzone" onClick={() => input.current.click()} onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); choose(e.dataTransfer.files); }}><UploadCloud size={38}/><strong>{files.length ? `${files.length} file${files.length > 1 ? 's' : ''} selected` : `Select ${config.images ? 'image' : config.documents ? 'document' : 'PDF'} file`}</strong><span>or drag and drop it here</span><input ref={input} type="file" accept={config.images ? 'image/jpeg,image/png' : config.documents ? '.doc,.docx,.xls,.xlsx,.ppt,.pptx,.html,.htm' : 'application/pdf'} multiple={config.multi} onChange={e => choose(e.target.files)} /></div>{(tool.action === 'split' || optionLabel) && <label>{tool.action === 'split' ? 'Pages or ranges' : optionLabel}<input value={option} onChange={e => setOption(e.target.value)} placeholder="1-3, 5" /></label>}{tool.action === 'rotate' && <label>Rotation<select value={option} onChange={e => setOption(e.target.value)}><option value="90">90° clockwise</option><option value="180">180°</option><option value="270">270° clockwise</option></select></label>}{tool.action === 'watermark' && <label>Watermark text<input value={option} onChange={e => setOption(e.target.value)} /></label>}{error && <p className="error">{error}</p>}<button className="process" disabled={!files.length || busy} onClick={process}>{busy ? <><LoaderCircle className="spin" /> Processing…</> : `${tool.name} now`}</button></> : <><p className="modal-copy">This interface is ready; the processing service for {tool.name} is the next tool to add.</p><button className="process" onClick={onClose}>Got it</button></>}</section></div>;
}
