import React from 'react';
import { Combine, Scissors, FileX, Share2, Rows3, ScanLine, Minimize2, Wrench, ScanText, Image, FileText, Presentation, Sheet, Code2, RotateCw, ListOrdered, Stamp, Crop, Pencil, FilePenLine } from 'lucide-react';
const groups = [
  { title: 'ORGANIZE PDF', color: 'coral', tools: [['Merge PDF', Combine, 'merge'], ['Split PDF', Scissors, 'split'], ['Remove pages', FileX, 'remove-pages'], ['Extract pages', Share2, 'split'], ['Organize PDF', Rows3], ['Scan to PDF', ScanLine]] },
  { title: 'OPTIMIZE PDF', color: 'green', tools: [['Compress PDF', Minimize2], ['Repair PDF', Wrench], ['OCR PDF', ScanText]] },
  { title: 'CONVERT TO PDF', color: 'yellow', tools: [['JPG to PDF', Image, 'from-images'], ['PNG to PDF', Image, 'from-images'], ['WORD to PDF', FileText, 'office-to-pdf'], ['POWERPOINT to PDF', Presentation, 'office-to-pdf'], ['EXCEL to PDF', Sheet, 'office-to-pdf'], ['HTML to PDF', Code2, 'office-to-pdf']] },
  { title: 'CONVERT FROM PDF', color: 'blue', tools: [['PDF to JPG', Image, 'to-jpg'], ['PDF to PNG', Image, 'to-png'], ['PDF to WORD', FileText, 'to-word'], ['PDF to POWERPOINT', Presentation, 'to-powerpoint'], ['PDF to EXCEL', Sheet, 'to-excel'], ['PDF to PDF/A', FileText, 'rotate']] },
  { title: 'EDIT PDF', color: 'purple', tools: [['Rotate PDF', RotateCw, 'rotate'], ['Add page numbers', ListOrdered, 'page-numbers'], ['Add watermark', Stamp, 'watermark'], ['Crop PDF', Crop, 'crop'], ['Edit PDF', Pencil, 'edit-text'], ['PDF Forms', FilePenLine, 'forms']] }
];
const descriptions = { 'Merge PDF':'Combine multiple PDF files into one document.', 'Split PDF':'Separate selected pages into a new PDF file.', 'Remove pages':'Remove pages you no longer need.', 'JPG to PDF':'Convert one or more JPG images to PDF.', 'PNG to PDF':'Convert one or more PNG images to PDF.', 'PDF to JPG':'Save the first PDF page as a JPG image.', 'PDF to PNG':'Save the first PDF page as a PNG image.', 'PDF to WORD':'Convert a PDF to an editable Word file.', 'PDF to POWERPOINT':'Convert a PDF to a PowerPoint file.', 'PDF to EXCEL':'Convert a PDF to an Excel spreadsheet.', 'WORD to PDF':'Turn Word documents into PDF files.', 'POWERPOINT to PDF':'Turn presentations into PDF files.', 'EXCEL to PDF':'Turn spreadsheets into PDF files.', 'Rotate PDF':'Rotate every page of your PDF.', 'Add page numbers':'Add page numbering to your PDF.', 'Add watermark':'Add a custom text watermark.', 'Crop PDF':'Trim margins around your PDF pages.', 'Edit PDF':'Add text to the first PDF page.', 'PDF Forms':'Add a fillable text field.' };
export default function ToolGrid({ onSelect, filter = 'home' }) { const visible = groups.filter(group => filter === 'all' || filter === 'home' || (filter === 'edit' && group.title === 'EDIT PDF') || (filter === 'convert' && group.title.includes('CONVERT'))); if (filter === 'home') { const featured = groups.flatMap(group => group.tools.map(tool => ({ tool, color: group.color }))).filter(({ tool }) => tool[2]).slice(0, 15); return <section id="all-tools" className="tool-cards">{featured.map(({ tool: [name, Icon, action], color }) => <button className="tool-card" onClick={() => onSelect({ name, action })} key={name}><span className={`card-icon ${color}`}><Icon size={30}/></span><h2>{name}</h2><p>{descriptions[name] || 'Open this PDF tool to get started.'}</p></button>)}</section>; } return <section id="all-tools" className={`tool-grid ${filter !== 'all' ? 'tool-grid-compact' : ''}`}>{visible.map(group => <div className="tool-column" id={group.title.toLowerCase().replaceAll(' ', '-')} key={group.title}><h2>{group.title}</h2>{group.tools.map(([name, Icon, action]) => <button className="tool" onClick={() => onSelect({ name, action })} key={name}><span className={`tool-icon ${group.color}`}><Icon size={19}/></span><span>{name}</span>{!action && <small>Coming soon</small>}</button>)}</div>)}</section>; }
