import React, { useEffect, useState } from 'react';
import { Menu, Heart, Linkedin, Instagram } from 'lucide-react';
import ToolGrid from './components/ToolGrid';
import FileProcessorModal from './components/FileProcessorModal';
import HelpChat from './components/HelpChat';
import ReviewModal from './components/ReviewModal';
import { api } from './api';
export default function App() {
  const [tool, setTool] = useState(null); const [visitorId, setVisitorId] = useState(null); const [menuGroup, setMenuGroup] = useState(null); const [reviewOpen, setReviewOpen] = useState(false);
  useEffect(() => { api.post('/track-visit', { pageVisited: window.location.pathname }).then(({ data }) => setVisitorId(data.visitorId)).catch(() => {}); }, []);
  const goTo = id => document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'center' });
  return <><div className="header-area" onMouseLeave={() => setMenuGroup(null)}><header><a className="brand" href="#top"><span className="brand-mark"><Heart fill="currentColor" /></span><b>AHARNISH</b><em>PDF</em></a><nav><button onClick={() => setTool({ name: 'Merge PDF', action: 'merge' })}>MERGE PDF</button><button onClick={() => setTool({ name: 'Split PDF', action: 'split' })}>SPLIT PDF</button><button onMouseEnter={() => setMenuGroup('edit')} onClick={() => goTo('edit-pdf')}>EDIT PDF</button><button onMouseEnter={() => setMenuGroup('convert')} onClick={() => goTo('convert-to-pdf')}>CONVERT PDF</button><button className="all" onMouseEnter={() => setMenuGroup('all')} onClick={() => goTo('all-tools')}>ALL TOOLS</button></nav><HelpChat /><button className="menu" onClick={() => goTo('all-tools')}><Menu /></button></header>{menuGroup && <div className={`mega-menu ${menuGroup === 'all' ? 'mega-menu-all' : ''}`}><ToolGrid filter={menuGroup} onSelect={tool => { setTool(tool); setMenuGroup(null); }} /></div>}</div><main id="top"><section className="hero"><p>AHARNISH PDF WORKSPACE</p><h1>Make every document move effortlessly</h1><p className="sub">A focused set of practical PDF tools, designed for your daily work.</p></section><ToolGrid onSelect={setTool} /></main><footer><section className="about-profile"><img src="/images/aharnish-atul.jpg" alt="Aharnish Atul"/><div><h2>About Us</h2><p>Aharnish PDF is built by <strong>Aharnish Atul</strong> to creating effortless digital solutions for your daily work.</p></div></section><section><h3>Contact</h3><a href="mailto:atulaharnish10@gmail.com">atulaharnish10@gmail.com</a><p>Kaveri 1, Vastu Vihar, near Madhubani Medical College,<br/>Madhubani, Bihar 847211</p></section><section><h3>Connect</h3><div className="social-links"><a href="https://www.linkedin.com/in/aharnishatul/" target="_blank" rel="noreferrer" aria-label="LinkedIn"><Linkedin /></a><a href="https://www.instagram.com/aharnish10/" target="_blank" rel="noreferrer" aria-label="Instagram"><Instagram /></a></div></section></footer>{tool && <FileProcessorModal tool={tool} visitorId={visitorId} onClose={() => setTool(null)} onCompleted={() => setReviewOpen(true)} />}{reviewOpen && <ReviewModal onClose={() => setReviewOpen(false)} />}</>;
}
